language: java
cache:
  timeout: 1000
  directories:
  - $HOME/.m2
jdk:
- openjdk8
- openjdk11
node_js:
  - "8.11.4"
os:
  - linux
env:
 - TEST_CASE="RepositoryApplication"
 - TEST_CASE="RestApplication"
 - TEST_CASE="AngularApplication"
 - TEST_CASE="AngularMicroService"
 - TEST_CASE="ReactJSApplication"
 - TEST_CASE="ReactJSMicroService"
before_install:
    - npm install -g npm
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn -v
    - export M2_HOME=/usr/local/maven-3.5.2
    - curl -o $HOME/.m2/settings.xml https://raw.githubusercontent.com/jeddict/netbeans-module-repository/master/settings.xml

    - git clone https://github.com/jeddict/netbeans-modeler.git ~/builds/netbeans-modeler
    - pushd ~/builds/netbeans-modeler
    - mvn clean install -q
    - popd

    - git clone https://github.com/jeddict/jeddict.git ~/builds/jeddict
    - pushd ~/builds/jeddict
    - mvn clean install -DskipTests -q
    - popd

    - git clone https://github.com/jeddict/jeddict-extensions.git ~/builds/jeddict-extensions
    - pushd ~/builds/jeddict-extensions
    - mvn clean install -q
    - popd

    - git clone https://github.com/jeddict/hipee.git ~/builds/hipee
    - pushd ~/builds/hipee
    - mvn clean install -q
    - popd


    
script:
    - mvn test -B -Dtestcase=${TEST_CASE}
