language: java
cache:
  timeout: 1000
  directories:
  - $HOME/.m2
jdk:
- openjdk8
- openjdk9
- openjdk10
- openjdk11
node_js:
  - "8.11.4"
os:
  - linux
  - osx
before_install:
    # Upgrade NPM
    - npm install -g npm
    # Install with Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn -v

    - git clone https://github.com/jeddict/netbeans-modeler.git ~/builds/netbeans-modeler
    - pushd ~/builds/netbeans-modeler/modeler-lib/repository/org/analytics/analytics/1.0
    - mvn install:install-file -Dfile=analytics-1.0.jar -DgroupId=org.analytics -DartifactId=analytics -Dversion=1.0 -Dpackaging=jar
    - popd
    - pushd ~/builds/netbeans-modeler
    - mvn clean install
    - popd

    - git clone https://github.com/jeddict/jeddict.git ~/builds/jeddict
    - pushd ~/builds/jeddict/jcode-core/repository/org/graalvm/graalvm/graaljs/1.0.0-rc6
    - mvn install:install-file -Dfile=graaljs-1.0.0-rc6.jar -DgroupId=org.graalvm -DartifactId=graaljs -Dversion=1.0.0-rc6 -Dpackaging=jar
    - popd
    - pushd ~/builds/jeddict/jcode-core/repository/org/graalvm/graalvm/graaljs-scriptengine/1.0.0-rc6
    - mvn install:install-file -Dfile=graaljs-scriptengine-1.0.0-rc6.jar -DgroupId=org.graalvm -DartifactId=graaljs-scriptengine -Dversion=1.0.0-rc6 -Dpackaging=jar
    - popd
    - pushd ~/builds/jeddict/jcode-core/repository/org/graalvm/graalvm/tregex/1.0.0-rc6
    - mvn install:install-file -Dfile=tregex-1.0.0-rc6.jar -DgroupId=org.graalvm -DartifactId=tregex -Dversion=1.0.0-rc6 -Dpackaging=jar
    - popd
    - pushd ~/builds/jeddict
    - mvn clean install -DskipTests
    - popd

    - git clone https://github.com/jeddict/jeddict-extensions.git ~/builds/jeddict-extensions
    - pushd ~/builds/jeddict-extensions
    - mvn clean install
    - popd

    - git clone https://github.com/jeddict/hipee.git ~/builds/hipee
    - pushd ~/builds/hipee
    - mvn clean install
    - popd
    
    - export M2_HOME=/usr/local/maven-3.5.2
    
script:
    - mvn test -B -Dtestcase=AngularApplicationTest
